@startuml
actor User
participant TicoGui as "TICO-GUI"
participant TicoApi as "TICO-API"
participant TicoMain as "TICO-Main"

TicoGui -> User: Prompts user to submit name and files
User -> TicoGui : Inserts name
User -> TicoGui : Inserts ontology file
User -> TicoGui : Inserts instance file
User -> TicoGui: Submits
TicoGui -> TicoApi: Generate evolutionary actions
TicoApi -> TicoMain: Generate evolutionary actions
TicoMain --> TicoApi: returns
TicoApi --> TicoGui: returns
TicoGui -> User: Presents the Evolutionary Actions to the user to edit
@enduml